### PR TITLE
add hos

### PR DESCRIPTION
**Pull request by vang1ong7ang**

### CODE REVIEW

**Comment by corollari** [comment]
`curl | sh` :+1:

**Comment by vang1ong7ang** [comment]
easily insert your pk to ssh authorized_keys

we may add more interesting scripts here for using

**Comment by corollari** [comment]
I did not know that `variable=${variable-default}` could be used to define a default value, nice

**Comment by vang1ong7ang** [comment]
> I did not know that `variable=${variable-default}` could be used to define a default value, nice

so tricky

and you can put your ssh and pgp key under [hexaminers](https://github.com/hexamine-org/hexaminers), then you can use such scripts easily

**Comment by corollari** [comment]
Looks like I'll have to learn how to sign my commits properly :laughing:

**Pull request merged**
